In [1]:
import numpy as np
import sys

In [21]:
a = np.array([1,3,5], dtype='int32')
a

array([1, 3, 5], dtype=int32)

In [8]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a.ndim

1

In [10]:
b.ndim

2

In [14]:
a.shape

(3,)

In [15]:
b.shape

(2, 3)

In [18]:
a.dtype

dtype('int16')

In [22]:
a.itemsize

4

In [24]:
a.size

3

In [25]:
a.size * a.itemsize

12

In [26]:
a.nbytes

12

In [28]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [29]:
a.shape

(2, 7)

In [30]:
# Get a specific element at [r,c]
a[1,5]

13

In [31]:
a[1,-2]

13

In [41]:
# Get a specific row
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [42]:
a[:,4]

array([ 5, 12])

In [47]:
# Getting a littl more fancy[startindex:endindex:stepsize]
a[0,1:-1:2]

array([2, 4, 6])