[YouTube NumPy教程](https://www.youtube.com/watch?v=QUT1VHiLmmI)

In [1]:
import numpy as np
import sys

In [21]:
a = np.array([1,3,5], dtype='int32')
a

array([1, 3, 5], dtype=int32)

In [8]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a.ndim

1

In [10]:
b.ndim

2

In [14]:
a.shape

(3,)

In [15]:
b.shape

(2, 3)

In [18]:
a.dtype

dtype('int16')

In [22]:
a.itemsize

4

In [24]:
a.size

3

In [25]:
a.size * a.itemsize

12

In [26]:
a.nbytes

12

In [28]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [29]:
a.shape

(2, 7)

In [30]:
# Get a specific element at [r,c]
a[1,5]

13

In [31]:
a[1,-2]

13

In [41]:
# Get a specific row
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [42]:
a[:,4]

array([ 5, 12])

In [47]:
# Getting a littl more fancy[startindex:endindex:stepsize]
a[0,1:-1:2]

array([2, 4, 6])

In [48]:
a[1,5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [49]:
a[:,2] = [100,200]
a

array([[  1,   2, 100,   4,   5,   6,   7],
       [  8,   9, 200,  11,  12,  20,  14]])

3d example

In [50]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c.ndim)

3


In [57]:
print(c[:,:,1])

[[2 4]
 [6 8]]


In [58]:
new_np_array = np.full((2, 2), 100)
new_np_array

array([[100, 100],
       [100, 100]])

In [60]:
another_np_array = np.full_like(a, 15)
another_np_array

array([[15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15]])

In [61]:
random_np_array = np.random.rand(3,2)
random_np_array

array([[0.34545697, 0.2046749 ],
       [0.69408938, 0.8581633 ],
       [0.82797124, 0.79908953]])

In [63]:
random_np_array = np.random.randn(4,3)
random_np_array

array([[ 0.29106226,  1.68980102, -0.69594986],
       [ 0.16252536,  0.58481631,  0.40918749],
       [ 0.64955116, -0.08025203,  2.5053461 ],
       [ 0.1603645 , -1.33471753,  2.16820289]])

In [66]:
random_np_array = np.random.random_sample(a.shape)
random_np_array

array([[0.39924483, 0.08082318, 0.78562969, 0.6593738 , 0.63061891,
        0.70004599, 0.75839132],
       [0.5809526 , 0.01289913, 0.80561911, 0.93301894, 0.60423794,
        0.96659468, 0.41050481]])

In [67]:
# Random Integer values
random_int_np_array = np.random.randint(1, 5, size = (3,4))
random_int_np_array

array([[2, 3, 1, 3],
       [1, 4, 1, 1],
       [3, 2, 1, 2]])

In [69]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [80]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [97]:
full_matrix = np.ones((5,5))
full_matrix.shape

(5, 5)

In [90]:
zero_matrix = np.zeros((3,3))
print(zero_matrix)
zero_matrix[1,1] = 9
print(zero_matrix)
zero_matrix.shape

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


(3, 3)

In [102]:
print(full_matrix.shape)
# full_matrix
full_matrix[1:-1,1:-1] = zero_matrix
full_matrix

(5, 5)


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [110]:
first_array = np.array([1,2,3])
second_array = first_array.copy()
second_array[0] = 100
print(second_array)
print(first_array)

[100   2   3]
[1 2 3]


In [111]:
first = np.array([1,2,3,4])
print(first)

[1 2 3 4]


In [112]:
first + 2

array([3, 4, 5, 6])

In [113]:
first - 2

array([-1,  0,  1,  2])

In [116]:
first / 2

array([0.5, 1. , 1.5, 2. ])

In [117]:
np.sin(first)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [122]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)
np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [123]:
# Find the determinant
c = np.identity(5)
np.linalg.det(c)

1.0

In [138]:
stats = np.array([[1,2,3],[4,5,6]])
print(f"min = {np.min(stats)}")
print(f"max = {np.max(stats)}")
print(f"min in each row = {np.min(stats, axis=1)}")
np.min(stats, axis=1)

min = 1
max = 6
min in each row = [1 4]


array([1, 4])

In [142]:
np.sum(stats, axis=1)
np.sum(stats, axis=0)
# print(np.sum(stats, axis=1))
# print(np.sum(stats, axis=0))

array([5, 7, 9])

In [158]:
before = np.array([[1,2,3,4], [5,6,7,8]])
after = before.reshape(4,2)
print(after)

new_after = before.reshape(8,1)
print(new_after)


another_after = before.reshape(2,2,2)
print(another_after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**Vertically stacking vectors**

In [161]:
row1 = np.array([1,2,3,4])
row2 = np.array([5,6,7,8])

np.vstack([row1, row2, row2, row2, row1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

**Horizontal stack**

In [167]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2)
np.hstack([h1, h2])

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

**Load data from file**

In [168]:
filedata = np.genfromtxt('sample_data.txt', delimiter=',')
filedata

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
       [100., 200., 300., 400., 500., 600., 700., 800., 900.]])

In [171]:
filedata = filedata.astype('int32')
filedata

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9],
       [100, 200, 300, 400, 500, 600, 700, 800, 900]], dtype=int32)

In [173]:
filedata[filedata > 50]

array([100, 200, 300, 400, 500, 600, 700, 800, 900], dtype=int32)

In [178]:
# You can index with a list in NumPy

arr = np.array([1,2,3,4,5,6,7,8,9])
arr[[1,3,5,7]]

array([2, 4, 6, 8])

In [180]:
filedata

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9],
       [100, 200, 300, 400, 500, 600, 700, 800, 900]], dtype=int32)

In [182]:
np.any(filedata > 100, axis=0)

array([False,  True,  True,  True,  True,  True,  True,  True,  True])

In [183]:
np.all(filedata > 5, axis=0)

array([False, False, False, False, False,  True,  True,  True,  True])

In [193]:
(filedata > 10) & (filedata < 300)

array([[False, False, False, False, False, False, False, False, False],
       [ True,  True, False, False, False, False, False, False, False]])

In [199]:
new_array = np.arange(1, 31)
# new_array
new_array = new_array.reshape(6,5)
new_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [200]:
subarray = new_array[2:4,0:2]
subarray

array([[11, 12],
       [16, 17]])

In [214]:
diag = new_array[[0,1,2,3],[1,2,3,4]]
diag

array([ 2,  8, 14, 20])

In [238]:
block = new_array[[0,4,5], 3:]
block

array([[ 4,  5],
       [24, 25],
       [29, 30]])