[YouTube NumPy教程](https://www.youtube.com/watch?v=QUT1VHiLmmI)

In [262]:
import numpy as np
import sys

In [263]:
a = np.array([1,3,5], dtype='int32')
a.ndim

1

In [264]:
b = np.array([[1,2,3],[4,5,6]])
b.ndim

2

In [265]:
a.ndim

1

In [266]:
b.ndim

2

In [267]:
a = np.array([[1,2,3], [4,5,6]], dtype='int32')

In [268]:
a.dtype

dtype('int32')

In [269]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 20, 30], [40, 50, 60], [70, 80, 90]]])
a.shape

(2, 3, 3)

In [270]:
a.ndim

3

In [271]:
a.shape

(2, 3, 3)

In [272]:
b.shape

(2, 3)

In [273]:
a.dtype

dtype('int64')

In [274]:
a.itemsize

8

In [275]:
a.size

18

In [276]:
a.size * a.itemsize

144

In [277]:
a.nbytes

144

In [278]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [279]:
a.shape

(2, 7)

In [280]:
# Get a specific element at [r,c]
a[1,5]

13

In [281]:
a[1,-2]

13

In [282]:
# Get a specific row
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [283]:
a[:,4]

array([ 5, 12])

In [284]:
# Getting a littl more fancy[startindex:endindex:stepsize]
a[0,1:-1:2]

array([2, 4, 6])

In [285]:
a[1,5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [286]:
a[:,2] = [100,200]
a

array([[  1,   2, 100,   4,   5,   6,   7],
       [  8,   9, 200,  11,  12,  20,  14]])

3d example

In [287]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c.ndim)

3


In [288]:
print(c[:,:,1])

[[2 4]
 [6 8]]


In [289]:
new_np_array = np.full((2, 2), 100)
new_np_array

array([[100, 100],
       [100, 100]])

In [290]:
another_np_array = np.full_like(a, 15)
another_np_array

array([[15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15]])

In [291]:
random_np_array = np.random.rand(3,2)
random_np_array

array([[0.94009781, 0.76414643],
       [0.09691402, 0.64795902],
       [0.31092633, 0.01399232]])

In [292]:
random_np_array = np.random.randn(4,3)
random_np_array

array([[ 0.39757134,  0.46001589,  1.00057032],
       [-1.54803707,  0.59560448, -1.06727914],
       [ 0.07293343,  0.55956704,  0.3958627 ],
       [-0.62576993,  1.39416868,  1.12964337]])

In [293]:
random_np_array = np.random.random_sample(a.shape)
random_np_array

array([[0.91159106, 0.12068731, 0.50370604, 0.83409911, 0.6287753 ,
        0.52778829, 0.32118411],
       [0.96906452, 0.69973553, 0.60215504, 0.2784231 , 0.7864491 ,
        0.59593275, 0.57269196]])

In [294]:
# Random Integer values
random_int_np_array = np.random.randint(1, 5, size = (3,4))
random_int_np_array

array([[1, 2, 1, 1],
       [2, 1, 3, 4],
       [3, 1, 1, 4]])

In [295]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [296]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [297]:
full_matrix = np.ones((5,5))
full_matrix.shape

(5, 5)

In [298]:
zero_matrix = np.zeros((3,3))
print(zero_matrix)
zero_matrix[1,1] = 9
print(zero_matrix)
zero_matrix.shape

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


(3, 3)

In [299]:
print(full_matrix.shape)
# full_matrix
full_matrix[1:-1,1:-1] = zero_matrix
full_matrix

(5, 5)


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [300]:
first_array = np.array([1,2,3])
second_array = first_array.copy()
second_array[0] = 100
print(second_array)
print(first_array)

[100   2   3]
[1 2 3]


In [301]:
first = np.array([1,2,3,4])
print(first)

[1 2 3 4]


In [302]:
first + 2

array([3, 4, 5, 6])

In [303]:
first - 2

array([-1,  0,  1,  2])

In [304]:
first / 2

array([0.5, 1. , 1.5, 2. ])

In [305]:
np.sin(first)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [306]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)
np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [307]:
# Find the determinant
c = np.identity(5)
np.linalg.det(c)

1.0

In [308]:
stats = np.array([[1,2,3],[4,5,6]])
print(f"min = {np.min(stats)}")
print(f"max = {np.max(stats)}")
print(f"min in each row = {np.min(stats, axis=1)}")
np.min(stats, axis=1)

min = 1
max = 6
min in each row = [1 4]


array([1, 4])

In [309]:
np.sum(stats, axis=1)
np.sum(stats, axis=0)
# print(np.sum(stats, axis=1))
# print(np.sum(stats, axis=0))

array([5, 7, 9])

In [310]:
before = np.array([[1,2,3,4], [5,6,7,8]])
after = before.reshape(4,2)
print(after)

new_after = before.reshape(8,1)
print(new_after)


another_after = before.reshape(2,2,2)
print(another_after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**Vertically stacking vectors**

In [311]:
row1 = np.array([1,2,3,4])
row2 = np.array([5,6,7,8])

np.vstack([row1, row2, row2, row2, row1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

**Horizontal stack**

In [312]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2)
np.hstack([h1, h2])

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

**Load data from file**

In [313]:
filedata = np.genfromtxt('sample_data.txt', delimiter=',')
filedata

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
       [100., 200., 300., 400., 500., 600., 700., 800., 900.]])

In [314]:
filedata = filedata.astype('int32')
filedata

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9],
       [100, 200, 300, 400, 500, 600, 700, 800, 900]], dtype=int32)

In [315]:
filedata[filedata > 50]

array([100, 200, 300, 400, 500, 600, 700, 800, 900], dtype=int32)

In [316]:
# You can index with a list in NumPy

arr = np.array([1,2,3,4,5,6,7,8,9])
arr[[1,3,5,7]]

array([2, 4, 6, 8])

In [317]:
filedata

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9],
       [100, 200, 300, 400, 500, 600, 700, 800, 900]], dtype=int32)

In [318]:
np.any(filedata > 100, axis=0)

array([False,  True,  True,  True,  True,  True,  True,  True,  True])

In [319]:
np.all(filedata > 5, axis=0)

array([False, False, False, False, False,  True,  True,  True,  True])

In [320]:
(filedata > 10) & (filedata < 300)

array([[False, False, False, False, False, False, False, False, False],
       [ True,  True, False, False, False, False, False, False, False]])

In [321]:
new_array = np.arange(1, 31)
# new_array
new_array = new_array.reshape(6,5)
new_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [322]:
subarray = new_array[2:4,0:2]
subarray

array([[11, 12],
       [16, 17]])

In [323]:
diag = new_array[[0,1,2,3],[1,2,3,4]]
diag

array([ 2,  8, 14, 20])

In [324]:
block = new_array[[0,4,5], 3:]
block

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [325]:
-3 % 12

9

In [326]:
-2 % 10

8

In [327]:
int(4 ** 0.5)

2

In [328]:
''.join(list('hello world!'))

'hello world!'

In [329]:
name = "John"
print("Hello, %s!" % name)

Hello, John!


In [330]:
import numpy as np
arr1 = np.empty([4, 2], dtype=np.uint16)

print('The 4x2 array is:\n', arr1)
print('The shape of the array is:', arr1.shape)
print('The dimension of the array is:', arr1.ndim)
print('The size of each element of array in bytes is', arr1.itemsize)

The 4x2 array is:
 [[ 6  0]
 [ 0  0]
 [15  0]
 [ 0  0]]
The shape of the array is: (4, 2)
The dimension of the array is: 2
The size of each element of array in bytes is 2


In [337]:
arr2 = np.arange(100, 200, 10).reshape(5, 2)
print(arr2)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [339]:
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print(sampleArray[:, 2])

[33 66 99]


In [356]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
odd_rows = sampleArray[1::2,:]
print('The array of odd rows is:\n', odd_rows)
even_columns = sampleArray[:,0::2].transpose()
print('The array of even columns is:\n', even_columns)

The array of odd rows is:
 [[15 18 21 24]
 [39 42 45 48]]
The array of even columns is:
 [[ 3 15 27 39 51]
 [ 9 21 33 45 57]]


In [357]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
result = arrayOne + arrayTwo
print('The result array is:\n', result)
print('The square of the result array is:\n', np.square(result))

The result array is:
 [[20 39 33]
 [25 25 28]]
The square of the result array is:
 [[ 400 1521 1089]
 [ 625  625  784]]
